export type Locale = 'ar' | 'en';

// ─── Arabic ──────────────────────────────────────────────────────────────────
const ar = {
  // ── Common ────────────────────────────────────────────────────────────────
  save: 'حفظ',
  cancel: 'إلغاء',
  confirm: 'تأكيد',
  delete: 'حذف',
  back: 'رجوع',
  retry: 'إعادة المحاولة',
  loading: 'جارٍ التحميل…',
  error: 'خطأ',
  success: 'تمّ بنجاح',
  submit: 'إرسال',
  close: 'إغلاق',
  yes: 'نعم',
  no: 'لا',
  optional: 'اختياري',
  required: 'مطلوب',
  search: 'بحث…',
  noData: 'لا توجد بيانات',

  // ── Auth — Login ───────────────────────────────────────────────────────────
  welcomeBack: 'أهلاً بعودتك',
  nationalId: 'رقم الهوية',
  nationalIdPlaceholder: 'رقم الهوية المكوّن من 10 أرقام',
  password: 'كلمة المرور',
  passwordPlaceholder: 'أدخل كلمة المرور',
  forgotPassword: 'نسيت كلمة المرور؟',
  signIn: 'تسجيل الدخول',
  signingIn: 'جارٍ تسجيل الدخول…',
  noAccount: 'تسجيل جديد',
  idRequired: 'أدخل رقم الهوية المكوّن من 10 أرقام',
  passwordRequired: 'كلمة المرور مطلوبة',
  loginFailed: 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
  signInFailed: 'فشل تسجيل الدخول',

  // ── Auth — Register ────────────────────────────────────────────────────────
  registerTitle: 'تسجيل موظف جديد',
  personalInfo: 'المعلومات الشخصية',
  firstNameAr: 'الاسم الأول',
  lastNameAr: 'اسم العائلة',
  phoneNumber: 'رقم الهاتف',
  phonePlaceholder: '+966 5X XXX XXXX',
  setPassword: 'إنشاء كلمة مرور',
  confirmPassword: 'تأكيد كلمة المرور',
  confirmPasswordPlaceholder: 'أعد إدخال كلمة المرور',
  passwordMinChars: 'الحد الأدنى 12 حرفاً. تضمّن أحرفاً كبيرة وصغيرة وأرقاماً ورموزاً.',
  dataProtected: 'بياناتك محمية وتُستخدم فقط لأغراض إدارة القوى العاملة.',
  submitting: 'جارٍ الإرسال…',
  submitRegistration: 'تقديم الطلب',
  alreadyRegistered: 'لديك حساب؟ تسجيل الدخول',
  idMustBe10Digits: 'يجب أن يكون رقم الهوية 10 أرقام بالضبط',
  passwordMin12: 'الحد الأدنى 12 حرفاً',
  passwordsNoMatch: 'كلمات المرور غير متطابقة',
  registrationFailed: 'فشل التسجيل. يرجى المحاولة مرة أخرى.',
  registrationError: 'خطأ في التسجيل',

  // ── Auth — OTP ─────────────────────────────────────────────────────────────
  verifyPhone: 'تحقق من رقم هاتفك',
  otpSentTo: 'أرسلنا رمز تحقق مكون من 6 أرقام إلى هاتفك.',
  otpExpiry: 'الرمز ينتهي خلال 5 دقائق',
  verifying: 'جارٍ التحقق…',
  verifyAccount: 'تحقق من الحساب',
  didntReceive: 'لم تستلم الرمز؟ ',
  resendIn: 'إعادة الإرسال بعد',
  resend: 'إعادة الإرسال',
  sending: 'جارٍ الإرسال…',
  incompleteCode: 'الرمز غير مكتمل',
  enter6DigitCode: 'أدخل رمز التحقق المكوّن من 6 أرقام.',
  sessionExpired: 'انتهت الجلسة. يرجى التسجيل مجدداً.',
  verificationFailed: 'فشل التحقق. يرجى المحاولة مرة أخرى.',
  verificationError: 'خطأ في التحقق',
  codeSent: 'تم إرسال الرمز',
  newCodeSent: 'تم إرسال رمز تحقق جديد إلى هاتفك.',
  resendFailed: 'فشل إعادة الإرسال',
  couldNotResend: 'تعذّر إعادة إرسال الرمز. يرجى المحاولة مرة أخرى.',

  // ── Auth — Forgot / Reset Password ────────────────────────────────────────
  forgotPasswordTitle: 'نسيت كلمة المرور',
  forgotPasswordDesc: 'أدخل رقم هويتك. سيتمكن مسؤول تقنية المعلومات من تزويدك برمز إعادة التعيين.',
  resetCodeSent: 'تم إرسال رمز الإعادة',
  resetCodeSentDesc: 'إذا كان الحساب نشطاً، تم إنشاء رمز إعادة تعيين. يرجى التواصل مع مسؤول تقنية المعلومات للحصول على الرمز.',
  enterResetCode: 'أدخل رمز الإعادة',
  backToSignIn: 'العودة إلى تسجيل الدخول',
  requestResetCode: 'طلب رمز الإعادة',

  resetPasswordTitle: 'إعادة تعيين كلمة المرور',
  resetPasswordDesc: 'أدخل الرمز الذي زوّدك به مسؤول تقنية المعلومات وكلمة المرور الجديدة.',
  resetCode: 'رمز الإعادة',
  resetCodePlaceholder: 'الصق رمز الإعادة هنا',
  newPassword: 'كلمة المرور الجديدة',
  newPasswordPlaceholder: 'أدخل كلمة المرور الجديدة',
  repeatPassword: 'تكرار كلمة المرور',
  repeatPasswordPlaceholder: 'أعد إدخال كلمة المرور الجديدة',
  setNewPassword: 'تعيين كلمة المرور الجديدة',
  resetting: 'جارٍ الإعادة…',
  passwordResetSuccess: 'تم إعادة تعيين كلمة المرور بنجاح. يرجى تسجيل الدخول.',
  passwordResetFailed: 'فشلت إعادة التعيين. يرجى طلب رمز جديد.',
  passwordMin8: 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',

  // ── Auth — Change Password ─────────────────────────────────────────────────
  changePasswordTitle: 'تعيين كلمة مرور',
  changePasswordDesc: 'تم إنشاء حسابك من قِبل المسؤول. يرجى تعيين كلمة مرور شخصية للمتابعة.',
  tempPassword: 'كلمة المرور المؤقتة',
  tempPasswordPlaceholder: 'أدخل كلمة المرور المؤقتة',
  savePassword: 'حفظ كلمة المرور',

  // ── Home / Check-in ────────────────────────────────────────────────────────
  goodMorning: 'صباح الخير',
  todaysStatus: 'حالة اليوم',
  present: 'حاضر',
  late: 'متأخر',
  absent: 'غائب',
  excused: 'معذور',
  holiday: 'إجازة',
  shift: 'الوردية',
  minLate: 'دقيقة تأخير',
  checkIn: 'تسجيل الحضور',
  checkInTime: 'وقت الحضور',
  duration: 'مدة العمل',
  shiftStartsAt: 'تبدأ الوردية الساعة',
  checkInOpens: 'يُفتح تسجيل الحضور قبل الوردية بـ30 دقيقة',
  attendanceRecorded: 'تم تسجيل الحضور',
  gettingLocation: 'جارٍ تحديد موقعك…',
  confirmCheckIn: 'تأكيد تسجيل الحضور',
  gpsWillBeRecorded: 'سيتم تسجيل موقعك الجغرافي.',
  checkInFailed: 'فشل تسجيل الحضور. يرجى المحاولة مرة أخرى.',
  viewAttendanceHistory: 'عرض سجل الحضور',
  noShiftToday: 'لا توجد وردية اليوم',
  restWell: 'استرح جيداً',

  // ── Announcements ──────────────────────────────────────────────────────────
  announcementsTitle: 'الإعلانات',
  pinned: 'مثبّت',
  noReplies: 'لا توجد ردود بعد',
  reply: 'رد',
  replies: 'ردود',
  newAnnouncement: 'إعلان جديد',
  announcementTitle: 'العنوان',
  announcementTitlePlaceholder: 'عنوان الإعلان…',
  message: 'الرسالة',
  messagePlaceholder: 'اكتب إعلانك هنا…',
  pinAnnouncement: 'تثبيت هذا الإعلان',
  emojiNotAllowed: 'الرموز التعبيرية غير مسموح بها في الإعلانات أو الردود.',
  noAnnouncements: 'لا توجد إعلانات بعد',
  replyPlaceholder: 'اكتب رداً…',
  post: 'نشر',
  notAllowed: 'غير مسموح',
  missingFields: 'حقول مفقودة',
  titleBodyRequired: 'العنوان والمحتوى مطلوبان.',
  deleteAnnouncement: 'حذف الإعلان',
  deleteAnnouncementConfirm: 'سيتم حذف الإعلان وجميع الردود نهائياً.',

  // ── Messages (group chat) ──────────────────────────────────────────────────
  messagesTitle: 'الرسائل',
  teamChat: 'محادثة الفريق',
  noMessages: 'لا توجد رسائل بعد',
  startConversation: 'كن أول من يبدأ المحادثة',
  typeMessage: 'اكتب رسالة…',
  deleteMessage: 'حذف الرسالة',
  deleteMessageConfirm: 'هل تريد حذف هذه الرسالة؟',
  sendFailed: 'فشل الإرسال',
  deleteFailed: 'فشل الحذف',

  // ── Profile ────────────────────────────────────────────────────────────────
  profileTitle: 'الملف الشخصي',
  administration: 'الإدارة',
  adminPanel: 'لوحة الإدارة',
  adminPanelDesc: 'إدارة الموظفين والحضور والجداول',
  account: 'الحساب',
  changePassword: 'تغيير كلمة المرور',
  changePasswordSubtitle: 'تحديث كلمة مرور الدخول',
  activeSessions: 'الجلسات النشطة',
  noActiveSessions: 'لا توجد جلسات نشطة',
  issuedAt: 'صدر في',
  lastUsed: 'آخر استخدام',
  revoke: 'إلغاء',
  signOut: 'تسجيل الخروج',
  signingOut: 'جارٍ الخروج…',
  signOutAllDevices: 'تسجيل الخروج من جميع الأجهزة',
  signOutAllConfirm: 'سيُنهي هذا الإجراء جميع الجلسات النشطة على كل الأجهزة.',
  revokeSession: 'إلغاء الجلسة',
  revokeSessionFor: 'إنهاء جلسة الجهاز',
  revokeSessionFailed: 'فشل إلغاء الجلسة',
  language: 'اللغة',
  languageAr: 'العربية',
  languageEn: 'English',
  languageChanged: 'تم تغيير اللغة',
  restartRequired: 'أعد تشغيل التطبيق لتطبيق التغيير الكامل.',

  // ── Shift Swap ─────────────────────────────────────────────────────────────
  shiftSwapTitle: 'تبديل المناوبات',
  newSwapRequest: 'طلب تبديل جديد',
  findEmployee: 'ابحث عن موظف للتبديل معه',
  searchByName: 'ابحث بالاسم…',
  selected: 'المحدد',
  myWeekStart: 'بداية أسبوعي (YYYY-MM-DD)',
  theirWeekStart: 'بداية أسبوعهم (YYYY-MM-DD)',
  reason: 'السبب (اختياري)',
  reasonPlaceholder: 'شرح مختصر',
  pending: 'قيد الانتظار',
  approved: 'موافق عليه',
  rejected: 'مرفوض',
  pastRequests: 'الطلبات السابقة',
  noSwapRequests: 'لا توجد طلبات تبديل',
  swapRequestedSuccess: 'تم تقديم طلب التبديل للموافقة عليه.',
  selectEmployee: 'اختر الموظف',
  selectEmployeePrompt: 'اختر الموظف الذي تريد التبديل معه.',
  missingDates: 'تواريخ مفقودة',
  enterBothDates: 'أدخل تاريخَي بداية الأسبوع (YYYY-MM-DD).',
  submittingSwap: 'جارٍ الإرسال…',
  submitRequest: 'إرسال الطلب',

  // ── Admin — Index ──────────────────────────────────────────────────────────
  adminTitle: 'لوحة الإدارة',
  pendingRegistrations: 'التسجيلات المعلّقة',
  noPendingRegistrations: 'لا توجد تسجيلات معلّقة',
  allCaughtUp: 'لا شيء معلّق!',
  employees: 'الموظفون',
  departments: 'الأقسام',
  schedules: 'الجداول',
  notifications: 'الإشعارات',
  attendance: 'الحضور',
  onDuty: 'في العمل',
  vacations: 'الإجازات',
  approve: 'موافقة',
  reject: 'رفض',
  approving: 'جارٍ الموافقة…',
  rejecting: 'جارٍ الرفض…',
  confirmApproval: 'تأكيد الموافقة',
  rejectRegistration: 'رفض التسجيل',
  rejectionReason: 'سبب الرفض (اختياري)',
  rejectionReasonPlaceholder: 'أدخل سبب الرفض',
  confirmReject: 'تأكيد الرفض',
  approvalFailed: 'فشلت الموافقة',
  rejectionFailed: 'فشل الرفض',
  pendingBadge: 'معلّق',
  registeredAt: 'تاريخ التسجيل',

  // ── Admin — On Duty ────────────────────────────────────────────────────────
  onDutyTitle: 'من في العمل',
  onDutySubtitle: 'من هم في العمل الآن',
  noOneCheckedIn: 'لم يسجّل أحد حضوره بعد',
  checkedOut: 'انتهى',
  total: 'الإجمالي',
  failedToLoadAttendance: 'فشل تحميل بيانات الحضور',

  // ── Admin — Employees ──────────────────────────────────────────────────────
  allEmployees: 'جميع الموظفون',
  employeeCount: 'موظف',
  noEmployeesFound: 'لا يوجد موظفون',
  failedToLoadEmployees: 'فشل تحميل الموظفين',

  // ── Admin — Vacations ──────────────────────────────────────────────────────
  vacationRequests: 'طلبات الإجازة',
  awaitingDeptManager: 'بانتظار مدير القسم',
  awaitingMainManager: 'بانتظار المدير الرئيسي',
  noPendingRequests: 'لا توجد طلبات معلّقة',
  noRequestsYet: 'لا توجد طلبات بعد',
  pendingCount: 'معلّق',
  allRequests: 'جميع الطلبات',
  days: 'أيام',
  approveVacation: 'الموافقة على الإجازة',
  rejectVacation: 'رفض الإجازة',
  failedToApprove: 'فشلت الموافقة',
  failedToReject: 'فشل الرفض',
  forwardToManager: 'إحالة إلى المدير',
  finalApprove: 'موافقة نهائية',
  reviewNotes: 'ملاحظات المراجعة (اختياري)',

  // ── Attendance History ─────────────────────────────────────────────────────
  attendanceHistory: 'سجل الحضور',
  failedToLoadHistory: 'فشل تحميل السجل',
};

// ─── English ──────────────────────────────────────────────────────────────────
const en: typeof ar = {
  // Common
  save: 'Save',
  cancel: 'Cancel',
  confirm: 'Confirm',
  delete: 'Delete',
  back: 'Back',
  retry: 'Retry',
  loading: 'Loading…',
  error: 'Error',
  success: 'Success',
  submit: 'Submit',
  close: 'Close',
  yes: 'Yes',
  no: 'No',
  optional: 'Optional',
  required: 'Required',
  search: 'Search…',
  noData: 'No data',

  // Auth — Login
  welcomeBack: 'Welcome Back',
  nationalId: 'National ID',
  nationalIdPlaceholder: '10-digit national ID',
  password: 'Password',
  passwordPlaceholder: 'Enter your password',
  forgotPassword: 'Forgot password?',
  signIn: 'Sign In',
  signingIn: 'Signing in…',
  noAccount: 'New Registration',
  idRequired: 'Enter your 10-digit national ID',
  passwordRequired: 'Password is required',
  loginFailed: 'Login failed. Please try again.',
  signInFailed: 'Sign In Failed',

  // Auth — Register
  registerTitle: 'New Employee Registration',
  personalInfo: 'Personal Information',
  firstNameAr: 'First Name (AR)',
  lastNameAr: 'Last Name (AR)',
  phoneNumber: 'Phone Number',
  phonePlaceholder: '+966 5X XXX XXXX',
  setPassword: 'Set Password',
  confirmPassword: 'Confirm Password',
  confirmPasswordPlaceholder: 'Re-enter password',
  passwordMinChars: 'Minimum 12 characters. Include uppercase, lowercase, numbers, and symbols.',
  dataProtected: 'Your data is protected and used only for workforce management purposes.',
  submitting: 'Submitting…',
  submitRegistration: 'Submit Registration',
  alreadyRegistered: 'Already registered? Sign In',
  idMustBe10Digits: 'ID number must be exactly 10 digits',
  passwordMin12: 'Minimum 12 characters',
  passwordsNoMatch: 'Passwords do not match',
  registrationFailed: 'Registration failed. Please try again.',
  registrationError: 'Registration Error',

  // Auth — OTP
  verifyPhone: 'Verify Your Phone',
  otpSentTo: 'We sent a 6-digit verification code to your phone.',
  otpExpiry: 'Code expires in 5 minutes',
  verifying: 'Verifying…',
  verifyAccount: 'Verify Account',
  didntReceive: "Didn't receive the code? ",
  resendIn: 'Resend in',
  resend: 'Resend',
  sending: 'Sending…',
  incompleteCode: 'Incomplete Code',
  enter6DigitCode: 'Please enter the full 6-digit code.',
  sessionExpired: 'Session expired. Please register again.',
  verificationFailed: 'Verification failed. Please try again.',
  verificationError: 'Verification Error',
  codeSent: 'Code Sent',
  newCodeSent: 'A new verification code has been sent to your phone.',
  resendFailed: 'Resend Failed',
  couldNotResend: 'Could not resend the code. Please try again.',

  // Auth — Forgot / Reset
  forgotPasswordTitle: 'Forgot Password',
  forgotPasswordDesc: 'Enter your National ID. Your IT administrator can then provide you with a reset code.',
  resetCodeSent: 'Reset Code Sent',
  resetCodeSentDesc: 'If an active account exists for that ID, a reset code has been generated. Please contact your IT administrator or HR department to obtain the code.',
  enterResetCode: 'Enter Reset Code',
  backToSignIn: 'Back to Sign In',
  requestResetCode: 'Request Reset Code',

  resetPasswordTitle: 'Reset Password',
  resetPasswordDesc: 'Enter the reset code provided by your IT administrator and your new password.',
  resetCode: 'Reset Code',
  resetCodePlaceholder: 'Paste your reset code',
  newPassword: 'New Password',
  newPasswordPlaceholder: 'Enter new password',
  repeatPassword: 'Confirm New Password',
  repeatPasswordPlaceholder: 'Repeat new password',
  setNewPassword: 'Set New Password',
  resetting: 'Resetting…',
  passwordResetSuccess: 'Your password has been reset. Please sign in.',
  passwordResetFailed: 'Reset failed. Please request a new code.',
  passwordMin8: 'Password must be at least 8 characters',

  // Auth — Change Password
  changePasswordTitle: 'Set Your Password',
  changePasswordDesc: 'Your account was created by an admin. Please set a personal password to continue.',
  tempPassword: 'Temporary Password',
  tempPasswordPlaceholder: 'Enter temporary password',
  savePassword: 'Save Password',

  // Home
  goodMorning: 'Good morning',
  todaysStatus: "Today's Status",
  present: 'Present',
  late: 'Late',
  absent: 'Absent',
  excused: 'Excused',
  holiday: 'Holiday',
  shift: 'Shift',
  minLate: 'min late',
  checkIn: 'Check In',
  checkInTime: 'Check-in',
  duration: 'Duration',
  shiftStartsAt: 'Shift Starts at',
  checkInOpens: 'Check-in opens 30 min before shift',
  attendanceRecorded: 'Attendance Recorded',
  gettingLocation: 'Getting your location…',
  confirmCheckIn: 'Confirm Check-in',
  gpsWillBeRecorded: 'Your GPS location will be recorded.',
  checkInFailed: 'Check-in failed. Please try again.',
  viewAttendanceHistory: 'View Attendance History',
  noShiftToday: 'No shift today',
  restWell: 'Rest well',

  // Announcements
  announcementsTitle: 'Announcements',
  pinned: 'Pinned',
  noReplies: 'No replies yet',
  reply: 'reply',
  replies: 'replies',
  newAnnouncement: 'New Announcement',
  announcementTitle: 'Title',
  announcementTitlePlaceholder: 'Announcement title…',
  message: 'Message',
  messagePlaceholder: 'Write your announcement here…',
  pinAnnouncement: 'Pin this announcement',
  emojiNotAllowed: 'Emojis and special symbols are not permitted.',
  noAnnouncements: 'No announcements yet',
  replyPlaceholder: 'Write a reply…',
  post: 'Post',
  notAllowed: 'Not Allowed',
  missingFields: 'Missing fields',
  titleBodyRequired: 'Title and body are required.',
  deleteAnnouncement: 'Delete Announcement',
  deleteAnnouncementConfirm: 'This will permanently delete the announcement and all replies.',

  // Profile
  profileTitle: 'Profile & Settings',
  administration: 'ADMINISTRATION',
  adminPanel: 'Admin Panel',
  adminPanelDesc: 'Manage employees, attendance & schedules',
  account: 'ACCOUNT',
  changePassword: 'Change Password',
  changePasswordSubtitle: 'Update your login password',
  activeSessions: 'ACTIVE SESSIONS',
  noActiveSessions: 'No active sessions',
  issuedAt: 'Issued',
  lastUsed: 'Last used',
  revoke: 'Revoke',
  signOut: 'Sign Out',
  signingOut: 'Signing out…',
  signOutAllDevices: 'Sign Out of All Devices',
  signOutAllConfirm: 'This will end all active sessions on every device.',
  revokeSession: 'Revoke Session',
  revokeSessionFor: 'End session for',
  revokeSessionFailed: 'Failed to revoke session',
  language: 'Language',
  languageAr: 'العربية',
  languageEn: 'English',
  languageChanged: 'Language Changed',
  restartRequired: 'Restart the app to fully apply the layout direction.',

  // Shift Swap
  shiftSwapTitle: 'Shift Swaps',
  newSwapRequest: 'New Swap Request',
  findEmployee: 'Find Employee to Swap With',
  searchByName: 'Search by name…',
  selected: 'Selected',
  myWeekStart: 'My Week Start (YYYY-MM-DD)',
  theirWeekStart: 'Their Week Start (YYYY-MM-DD)',
  reason: 'Reason (optional)',
  reasonPlaceholder: 'Brief explanation',
  pending: 'Pending',
  approved: 'Approved',
  rejected: 'Rejected',
  pastRequests: 'Past Requests',
  noSwapRequests: 'No Swap Requests',
  swapRequestedSuccess: 'Your shift swap request has been submitted for approval.',
  selectEmployee: 'Select Employee',
  selectEmployeePrompt: 'Please select the employee you want to swap with.',
  missingDates: 'Missing Dates',
  enterBothDates: 'Enter both week start dates (YYYY-MM-DD).',
  submittingSwap: 'Submitting…',
  submitRequest: 'Submit Request',

  // Admin — Index
  adminTitle: 'Admin Panel',
  pendingRegistrations: 'Pending Registrations',
  noPendingRegistrations: 'No pending registrations',
  allCaughtUp: 'All caught up!',
  employees: 'Employees',
  departments: 'Departments',
  schedules: 'Schedules',
  notifications: 'Notifications',
  attendance: 'Attendance',
  onDuty: 'On Duty',
  vacations: 'Vacations',
  approve: 'Approve',
  reject: 'Reject',
  approving: 'Approving…',
  rejecting: 'Rejecting…',
  confirmApproval: 'Confirm Approval',
  rejectRegistration: 'Reject Registration',
  rejectionReason: 'Reason (optional)',
  rejectionReasonPlaceholder: 'Enter rejection reason',
  confirmReject: 'Confirm Reject',
  approvalFailed: 'Approval failed',
  rejectionFailed: 'Rejection failed',
  pendingBadge: 'Pending',
  registeredAt: 'Registered',

  // Messages (group chat)
  messagesTitle: 'Messages',
  teamChat: 'Team Chat',
  noMessages: 'No messages yet',
  startConversation: 'Be the first to start the conversation',
  typeMessage: 'Type a message…',
  deleteMessage: 'Delete Message',
  deleteMessageConfirm: 'Do you want to delete this message?',
  sendFailed: 'Failed to send',
  deleteFailed: 'Failed to delete',

  // Admin — On Duty
  onDutyTitle: 'On Duty',
  onDutySubtitle: 'Who is at work right now',
  noOneCheckedIn: 'No one checked in yet',
  checkedOut: 'Checked out',
  total: 'Total',
  failedToLoadAttendance: 'Failed to load attendance',

  // Admin — Employees
  allEmployees: 'All Employees',
  employeeCount: 'employee(s)',
  noEmployeesFound: 'No employees found',
  failedToLoadEmployees: 'Failed to load employees',

  // Admin — Vacations
  vacationRequests: 'Vacation Requests',
  awaitingDeptManager: 'Awaiting Dept. Manager',
  awaitingMainManager: 'Awaiting Main Manager',
  noPendingRequests: 'No Pending Requests',
  noRequestsYet: 'No Requests Yet',
  pendingCount: 'Pending',
  allRequests: 'All Requests',
  days: 'day(s)',
  approveVacation: 'Approve Vacation',
  rejectVacation: 'Reject Vacation',
  failedToApprove: 'Failed to approve',
  failedToReject: 'Failed to reject',
  forwardToManager: 'Forward to Manager',
  finalApprove: 'Final Approve',
  reviewNotes: 'Review notes (optional)',

  // Attendance History
  attendanceHistory: 'Attendance History',
  failedToLoadHistory: 'Failed to load history',
};

export type StringKey = keyof typeof en;
export const translations: Record<Locale, Record<StringKey, string>> = { ar, en };
