// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/asa-designs/AuroraGradient.tsx": () => import("../components/mockups/asa-designs/AuroraGradient.tsx"),
  "./components/mockups/asa-designs/BoldGeometric.tsx": () => import("../components/mockups/asa-designs/BoldGeometric.tsx"),
  "./components/mockups/asa-designs/EmeraldEnterprise.tsx": () => import("../components/mockups/asa-designs/EmeraldEnterprise.tsx"),
  "./components/mockups/asa-designs/MidnightGlass.tsx": () => import("../components/mockups/asa-designs/MidnightGlass.tsx"),
  "./components/mockups/asa-designs/SoftBloom.tsx": () => import("../components/mockups/asa-designs/SoftBloom.tsx"),
  "./components/mockups/app-designs/ClassicGovt.tsx": () => import("../components/mockups/app-designs/ClassicGovt.tsx"),
  "./components/mockups/app-designs/EmeraldAuthority.tsx": () => import("../components/mockups/app-designs/EmeraldAuthority.tsx"),
  "./components/mockups/app-designs/EmeraldV2.tsx": () => import("../components/mockups/app-designs/EmeraldV2.tsx"),
  "./components/mockups/app-designs/PremiumDark.tsx": () => import("../components/mockups/app-designs/PremiumDark.tsx"),
  "./components/mockups/app-designs/SignInLetterhead.tsx": () => import("../components/mockups/app-designs/SignInLetterhead.tsx"),
  "./components/mockups/app-designs/SignInModern.tsx": () => import("../components/mockups/app-designs/SignInModern.tsx"),
  "./components/mockups/app-designs/SignInParchment.tsx": () => import("../components/mockups/app-designs/SignInParchment.tsx")
};
