kind = "mobile"
previewPath = "/mobile"
title = "ASA-Force"
version = "1.0.0"
id = "artifacts/asa-mobile"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/mobile" ]
localPort = 25112

[services.development]
run = "pnpm --filter @workspace/asa-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/asa-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/asa-mobile", "run", "serve" ]

[services.env]
PORT = "25112"
BASE_PATH = "/mobile"
